name: Update Script

on:
  schedule:
    - cron: "15 18 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Streak Tracker
        run: python tracker.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tracker.txt last_trace.txt
          git commit -m "Update streak" || echo "No changes to commit"
          git push

      - name: Update GitHub Streak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python script.py
